import Head from 'next/head';
import Image from 'next/image';
import About from '../components/About';
import Contact from '../components/Contact';
import Details from '../components/Details';
import Footer from '../components/Footer';
import Landing from '../components/Landing';
import Layout from '../components/Layout';

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout />
      <About />
      <Details />
      <Contact />
      <Footer />
    </div>
  );
}
