import Head from 'next/head';
import Image from 'next/image';
import Details from '../components/Details';
import Landing from '../components/Landing';
import Navbar from '../components/Navbar';
import Product from '../components/Product';

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Landing />
      <Product />
      <Details />
    </div>
  );
}
